bus1: fix coding style
Add missing space in ternary.

Fixes the following checkpatch output:

ERROR: spaces required around that ':' (ctx:VxW)

Introduced in 02f5769a990c (bus1: merge the bus2-branch into master,
2016-10-26)

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>