tests: hive: fix compile error of pthread_create
Change define of link libs to LDLIBS instead of CFLAGS
due to the error

test-hive.o: In function `test_hive':
test-hive.c:(.text+0x3fb): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

Signed-off-by: Phong Tran <tranmanphong@gmail.com>