tests: fix coding style
Fixes the following checkpatch output:

ERROR: "(foo*)" should be "(foo *)"

Introduced in 0f0bffdb4b91 (tests: restore active, pool, queue and user
tests, 2016-10-26)

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>