transaction: add space between void and * (#25)
Fixes the following checkpatch output:

ERROR: "(foo*)" should be "(foo *)"

Introduced in f937b12 (cgroup: write the cgroup of the sending task to
the pool, 2016-09-01)

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>